name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:3000

      - name: Run tests
        run: npm test
