name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
         type: environment
         required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: echo "Die Environment ist ${{ inputs.envitonment}}"
      - run: echo "Der Wert der Environment-Variable DECRIPTION ist ${{ vars.DESCRIPTION}}"
      - run: echo "Mein Benutzer-secret ist ist ${{ secrets.MONGODB_USERNAME}}"
